//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap { Locale(identifier: $0) } ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)

  /// Find first language and bundle for which the table exists
  fileprivate static func localeBundle(tableName: String, preferredLanguages: [String]) -> (Foundation.Locale, Foundation.Bundle)? {
    // Filter preferredLanguages to localizations, use first locale
    var languages = preferredLanguages
      .map { Locale(identifier: $0) }
      .prefix(1)
      .flatMap { locale -> [String] in
        if hostingBundle.localizations.contains(locale.identifier) {
          if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
            return [locale.identifier, language]
          } else {
            return [locale.identifier]
          }
        } else if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
          return [language]
        } else {
          return []
        }
      }

    // If there's no languages, use development language as backstop
    if languages.isEmpty {
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages = [developmentLocalization]
      }
    } else {
      // Insert Base as second item (between locale identifier and languageCode)
      languages.insert("Base", at: 1)

      // Add development language as backstop
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages.append(developmentLocalization)
      }
    }

    // Find first language for which table exists
    // Note: key might not exist in chosen language (in that case, key will be shown)
    for language in languages {
      if let lproj = hostingBundle.url(forResource: language, withExtension: "lproj"),
         let lbundle = Bundle(url: lproj)
      {
        let strings = lbundle.url(forResource: tableName, withExtension: "strings")
        let stringsdict = lbundle.url(forResource: tableName, withExtension: "stringsdict")

        if strings != nil || stringsdict != nil {
          return (Locale(identifier: language), lbundle)
        }
      }
    }

    // If table is available in main bundle, don't look for localized resources
    let strings = hostingBundle.url(forResource: tableName, withExtension: "strings", subdirectory: nil, localization: nil)
    let stringsdict = hostingBundle.url(forResource: tableName, withExtension: "stringsdict", subdirectory: nil, localization: nil)

    if strings != nil || stringsdict != nil {
      return (applicationLocale, hostingBundle)
    }

    // If table is not found for requested languages, key will be shown
    return nil
  }

  /// Load string from Info.plist file
  fileprivate static func infoPlistString(path: [String], key: String) -> String? {
    var dict = hostingBundle.infoDictionary
    for step in path {
      guard let obj = dict?[step] as? [String: Any] else { return nil }
      dict = obj
    }
    return dict?[key] as? String
  }

  static func validate() throws {
    try intern.validate()
  }

  #if os(iOS) || os(tvOS)
  /// This `R.storyboard` struct is generated, and contains static references to 3 storyboards.
  struct storyboard {
    /// Storyboard `EatList`.
    static let eatList = _R.storyboard.eatList()
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `TargetDetails`.
    static let targetDetails = _R.storyboard.targetDetails()

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "EatList", bundle: ...)`
    static func eatList(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.eatList)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "TargetDetails", bundle: ...)`
    static func targetDetails(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.targetDetails)
    }
    #endif

    fileprivate init() {}
  }
  #endif

  /// This `R.color` struct is generated, and contains static references to 3 colors.
  struct color {
    /// Color `AccentColor`.
    static let accentColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "AccentColor")
    /// Color `gradient-base`.
    static let gradientBase = Rswift.ColorResource(bundle: R.hostingBundle, name: "gradient-base")
    /// Color `gradient-secondary`.
    static let gradientSecondary = Rswift.ColorResource(bundle: R.hostingBundle, name: "gradient-secondary")

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "AccentColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func accentColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.accentColor, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "gradient-base", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func gradientBase(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.gradientBase, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "gradient-secondary", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func gradientSecondary(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.gradientSecondary, compatibleWith: traitCollection)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "AccentColor", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func accentColor(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.accentColor.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "gradient-base", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func gradientBase(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.gradientBase.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "gradient-secondary", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func gradientSecondary(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.gradientSecondary.name)
    }
    #endif

    fileprivate init() {}
  }

  /// This `R.image` struct is generated, and contains static references to 9 images.
  struct image {
    /// Image `Back`.
    static let back = Rswift.ImageResource(bundle: R.hostingBundle, name: "Back")
    /// Image `BlankState`.
    static let blankState = Rswift.ImageResource(bundle: R.hostingBundle, name: "BlankState")
    /// Image `ErrorIcon`.
    static let errorIcon = Rswift.ImageResource(bundle: R.hostingBundle, name: "ErrorIcon")
    /// Image `Icon`.
    static let icon = Rswift.ImageResource(bundle: R.hostingBundle, name: "Icon")
    /// Image `LocationUpdate`.
    static let locationUpdate = Rswift.ImageResource(bundle: R.hostingBundle, name: "LocationUpdate")
    /// Image `Pizzannotation`.
    static let pizzannotation = Rswift.ImageResource(bundle: R.hostingBundle, name: "Pizzannotation")
    /// Image `Placeholder`.
    static let placeholder = Rswift.ImageResource(bundle: R.hostingBundle, name: "Placeholder")
    /// Image `Rating`.
    static let rating = Rswift.ImageResource(bundle: R.hostingBundle, name: "Rating")
    /// Image `star`.
    static let star = Rswift.ImageResource(bundle: R.hostingBundle, name: "star")

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "Back", bundle: ..., traitCollection: ...)`
    static func back(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.back, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "BlankState", bundle: ..., traitCollection: ...)`
    static func blankState(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.blankState, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "ErrorIcon", bundle: ..., traitCollection: ...)`
    static func errorIcon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.errorIcon, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "Icon", bundle: ..., traitCollection: ...)`
    static func icon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.icon, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "LocationUpdate", bundle: ..., traitCollection: ...)`
    static func locationUpdate(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.locationUpdate, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "Pizzannotation", bundle: ..., traitCollection: ...)`
    static func pizzannotation(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.pizzannotation, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "Placeholder", bundle: ..., traitCollection: ...)`
    static func placeholder(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.placeholder, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "Rating", bundle: ..., traitCollection: ...)`
    static func rating(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.rating, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "star", bundle: ..., traitCollection: ...)`
    static func star(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.star, compatibleWith: traitCollection)
    }
    #endif

    fileprivate init() {}
  }

  /// This `R.info` struct is generated, and contains static references to 1 properties.
  struct info {
    struct uiApplicationSceneManifest {
      static let _key = "UIApplicationSceneManifest"
      static let uiApplicationSupportsMultipleScenes = false

      struct uiSceneConfigurations {
        static let _key = "UISceneConfigurations"

        struct uiWindowSceneSessionRoleApplication {
          struct defaultConfiguration {
            static let _key = "Default Configuration"
            static let uiSceneConfigurationName = infoPlistString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication", "Default Configuration"], key: "UISceneConfigurationName") ?? "Default Configuration"
            static let uiSceneDelegateClassName = infoPlistString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication", "Default Configuration"], key: "UISceneDelegateClassName") ?? "$(PRODUCT_MODULE_NAME).SceneDelegate"

            fileprivate init() {}
          }

          fileprivate init() {}
        }

        fileprivate init() {}
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }

  /// This `R.nib` struct is generated, and contains static references to 9 nibs.
  struct nib {
    /// Nib `AddressDetailsTableViewCell`.
    static let addressDetailsTableViewCell = _R.nib._AddressDetailsTableViewCell()
    /// Nib `AlertView`.
    static let alertView = _R.nib._AlertView()
    /// Nib `BaseDetailsTableViewCell`.
    static let baseDetailsTableViewCell = _R.nib._BaseDetailsTableViewCell()
    /// Nib `EatListBlankTableViewCell`.
    static let eatListBlankTableViewCell = _R.nib._EatListBlankTableViewCell()
    /// Nib `EatListTableViewCell`.
    static let eatListTableViewCell = _R.nib._EatListTableViewCell()
    /// Nib `HighlightsTableViewCell`.
    static let highlightsTableViewCell = _R.nib._HighlightsTableViewCell()
    /// Nib `ImageHeaderTableViewCell`.
    static let imageHeaderTableViewCell = _R.nib._ImageHeaderTableViewCell()
    /// Nib `SimpleCarouselItemCell`.
    static let simpleCarouselItemCell = _R.nib._SimpleCarouselItemCell()
    /// Nib `SimpleCarouselItemView`.
    static let simpleCarouselItemView = _R.nib._SimpleCarouselItemView()

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "AddressDetailsTableViewCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.addressDetailsTableViewCell) instead")
    static func addressDetailsTableViewCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.addressDetailsTableViewCell)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "AlertView", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.alertView) instead")
    static func alertView(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.alertView)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "BaseDetailsTableViewCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.baseDetailsTableViewCell) instead")
    static func baseDetailsTableViewCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.baseDetailsTableViewCell)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "EatListBlankTableViewCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.eatListBlankTableViewCell) instead")
    static func eatListBlankTableViewCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.eatListBlankTableViewCell)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "EatListTableViewCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.eatListTableViewCell) instead")
    static func eatListTableViewCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.eatListTableViewCell)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "HighlightsTableViewCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.highlightsTableViewCell) instead")
    static func highlightsTableViewCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.highlightsTableViewCell)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "ImageHeaderTableViewCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.imageHeaderTableViewCell) instead")
    static func imageHeaderTableViewCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.imageHeaderTableViewCell)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "SimpleCarouselItemCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.simpleCarouselItemCell) instead")
    static func simpleCarouselItemCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.simpleCarouselItemCell)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "SimpleCarouselItemView", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.simpleCarouselItemView) instead")
    static func simpleCarouselItemView(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.simpleCarouselItemView)
    }
    #endif

    static func addressDetailsTableViewCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> AddressDetailsTableViewCell? {
      return R.nib.addressDetailsTableViewCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? AddressDetailsTableViewCell
    }

    static func alertView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
      return R.nib.alertView.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
    }

    static func baseDetailsTableViewCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> BaseDetailsTableViewCell? {
      return R.nib.baseDetailsTableViewCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? BaseDetailsTableViewCell
    }

    static func eatListBlankTableViewCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> EatListBlankTableViewCell? {
      return R.nib.eatListBlankTableViewCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? EatListBlankTableViewCell
    }

    static func eatListTableViewCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> EatListTableViewCell? {
      return R.nib.eatListTableViewCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? EatListTableViewCell
    }

    static func highlightsTableViewCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> HighlightsTableViewCell? {
      return R.nib.highlightsTableViewCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? HighlightsTableViewCell
    }

    static func imageHeaderTableViewCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> ImageHeaderTableViewCell? {
      return R.nib.imageHeaderTableViewCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? ImageHeaderTableViewCell
    }

    static func simpleCarouselItemCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> SimpleCarouselItemCell? {
      return R.nib.simpleCarouselItemCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? SimpleCarouselItemCell
    }

    static func simpleCarouselItemView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
      return R.nib.simpleCarouselItemView.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
    }

    fileprivate init() {}
  }

  /// This `R.string` struct is generated, and contains static references to 1 localization tables.
  struct string {
    /// This `R.string.localizable` struct is generated, and contains static references to 18 localization keys.
    struct localizable {
      /// Value: Close
      static let buttonTitleClose = Rswift.StringResource(key: "ButtonTitle.Close", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Cost for two
      static let targetDetailsBaseDetailsCostForTwoPrefix = Rswift.StringResource(key: "TargetDetails.BaseDetails.CostForTwo.Prefix", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Eat List
      static let appName = Rswift.StringResource(key: "AppName", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Oops!
      static let errorCommonTitle = Rswift.StringResource(key: "Error.Common.Title", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Please allow Eat List to access your location for the app to work.
      static let errorLocationPermissionDeniedMessage = Rswift.StringResource(key: "Error.Location.PermissionDenied.Message", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Please try again in a bit.
      static let errorLocationGeneralFailureMessage = Rswift.StringResource(key: "Error.Location.GeneralFailure.Message", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Review(s)
      static let targetDetailsBaseDetailsReviewsSuffix = Rswift.StringResource(key: "TargetDetails.BaseDetails.ReviewsSuffix", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Settings
      static let errorLocationPermissionDeniedPrimaryButtonTitle = Rswift.StringResource(key: "Error.Location.PermissionDenied.PrimaryButtonTitle", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Something went wrong. Please try again in a bit. 
      static let errorCommonMessage = Rswift.StringResource(key: "Error.Common.Message", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Try again in a bit.
      static let errorRestaurantAPIGeneralFailureMessage = Rswift.StringResource(key: "Error.RestaurantAPI.GeneralFailure.Message", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: We can't seem to find you!
      static let errorLocationGeneralFailureTitle = Rswift.StringResource(key: "Error.Location.GeneralFailure.Title", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: We couldn't get your location!
      static let errorLocationPermissionDeniedTitle = Rswift.StringResource(key: "Error.Location.PermissionDenied.Title", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: We lost the list, boss!
      static let errorRestaurantAPIGeneralFailureTitle = Rswift.StringResource(key: "Error.RestaurantAPI.GeneralFailure.Title", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: We lost you!
      static let errorConnectivityTitle = Rswift.StringResource(key: "Error.Connectivity.Title", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: You're currently offline! Please check your internet connection and try again.
      static let errorConnectivityMessage = Rswift.StringResource(key: "Error.Connectivity.Message", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: approx.
      static let targetDetailsBaseDetailsCostForTwoApprox = Rswift.StringResource(key: "TargetDetails.BaseDetails.CostForTwo.Approx", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: for two
      static let eatListPriceDetailsSuffix = Rswift.StringResource(key: "EatList.PriceDetails.Suffix", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: without alcohol
      static let targetDetailsBaseDetailsCostForTwoWithoutAlcohol = Rswift.StringResource(key: "TargetDetails.BaseDetails.CostForTwo.WithoutAlcohol", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)

      /// Value: Close
      static func buttonTitleClose(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("ButtonTitle.Close", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "ButtonTitle.Close"
        }

        return NSLocalizedString("ButtonTitle.Close", bundle: bundle, comment: "")
      }

      /// Value: Cost for two
      static func targetDetailsBaseDetailsCostForTwoPrefix(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("TargetDetails.BaseDetails.CostForTwo.Prefix", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "TargetDetails.BaseDetails.CostForTwo.Prefix"
        }

        return NSLocalizedString("TargetDetails.BaseDetails.CostForTwo.Prefix", bundle: bundle, comment: "")
      }

      /// Value: Eat List
      static func appName(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("AppName", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "AppName"
        }

        return NSLocalizedString("AppName", bundle: bundle, comment: "")
      }

      /// Value: Oops!
      static func errorCommonTitle(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("Error.Common.Title", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "Error.Common.Title"
        }

        return NSLocalizedString("Error.Common.Title", bundle: bundle, comment: "")
      }

      /// Value: Please allow Eat List to access your location for the app to work.
      static func errorLocationPermissionDeniedMessage(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("Error.Location.PermissionDenied.Message", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "Error.Location.PermissionDenied.Message"
        }

        return NSLocalizedString("Error.Location.PermissionDenied.Message", bundle: bundle, comment: "")
      }

      /// Value: Please try again in a bit.
      static func errorLocationGeneralFailureMessage(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("Error.Location.GeneralFailure.Message", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "Error.Location.GeneralFailure.Message"
        }

        return NSLocalizedString("Error.Location.GeneralFailure.Message", bundle: bundle, comment: "")
      }

      /// Value: Review(s)
      static func targetDetailsBaseDetailsReviewsSuffix(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("TargetDetails.BaseDetails.ReviewsSuffix", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "TargetDetails.BaseDetails.ReviewsSuffix"
        }

        return NSLocalizedString("TargetDetails.BaseDetails.ReviewsSuffix", bundle: bundle, comment: "")
      }

      /// Value: Settings
      static func errorLocationPermissionDeniedPrimaryButtonTitle(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("Error.Location.PermissionDenied.PrimaryButtonTitle", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "Error.Location.PermissionDenied.PrimaryButtonTitle"
        }

        return NSLocalizedString("Error.Location.PermissionDenied.PrimaryButtonTitle", bundle: bundle, comment: "")
      }

      /// Value: Something went wrong. Please try again in a bit. 
      static func errorCommonMessage(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("Error.Common.Message", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "Error.Common.Message"
        }

        return NSLocalizedString("Error.Common.Message", bundle: bundle, comment: "")
      }

      /// Value: Try again in a bit.
      static func errorRestaurantAPIGeneralFailureMessage(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("Error.RestaurantAPI.GeneralFailure.Message", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "Error.RestaurantAPI.GeneralFailure.Message"
        }

        return NSLocalizedString("Error.RestaurantAPI.GeneralFailure.Message", bundle: bundle, comment: "")
      }

      /// Value: We can't seem to find you!
      static func errorLocationGeneralFailureTitle(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("Error.Location.GeneralFailure.Title", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "Error.Location.GeneralFailure.Title"
        }

        return NSLocalizedString("Error.Location.GeneralFailure.Title", bundle: bundle, comment: "")
      }

      /// Value: We couldn't get your location!
      static func errorLocationPermissionDeniedTitle(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("Error.Location.PermissionDenied.Title", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "Error.Location.PermissionDenied.Title"
        }

        return NSLocalizedString("Error.Location.PermissionDenied.Title", bundle: bundle, comment: "")
      }

      /// Value: We lost the list, boss!
      static func errorRestaurantAPIGeneralFailureTitle(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("Error.RestaurantAPI.GeneralFailure.Title", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "Error.RestaurantAPI.GeneralFailure.Title"
        }

        return NSLocalizedString("Error.RestaurantAPI.GeneralFailure.Title", bundle: bundle, comment: "")
      }

      /// Value: We lost you!
      static func errorConnectivityTitle(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("Error.Connectivity.Title", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "Error.Connectivity.Title"
        }

        return NSLocalizedString("Error.Connectivity.Title", bundle: bundle, comment: "")
      }

      /// Value: You're currently offline! Please check your internet connection and try again.
      static func errorConnectivityMessage(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("Error.Connectivity.Message", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "Error.Connectivity.Message"
        }

        return NSLocalizedString("Error.Connectivity.Message", bundle: bundle, comment: "")
      }

      /// Value: approx.
      static func targetDetailsBaseDetailsCostForTwoApprox(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("TargetDetails.BaseDetails.CostForTwo.Approx", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "TargetDetails.BaseDetails.CostForTwo.Approx"
        }

        return NSLocalizedString("TargetDetails.BaseDetails.CostForTwo.Approx", bundle: bundle, comment: "")
      }

      /// Value: for two
      static func eatListPriceDetailsSuffix(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("EatList.PriceDetails.Suffix", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "EatList.PriceDetails.Suffix"
        }

        return NSLocalizedString("EatList.PriceDetails.Suffix", bundle: bundle, comment: "")
      }

      /// Value: without alcohol
      static func targetDetailsBaseDetailsCostForTwoWithoutAlcohol(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("TargetDetails.BaseDetails.CostForTwo.WithoutAlcohol", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "TargetDetails.BaseDetails.CostForTwo.WithoutAlcohol"
        }

        return NSLocalizedString("TargetDetails.BaseDetails.CostForTwo.WithoutAlcohol", bundle: bundle, comment: "")
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }

  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }

    fileprivate init() {}
  }

  fileprivate class Class {}

  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    #if os(iOS) || os(tvOS)
    try nib.validate()
    #endif
    #if os(iOS) || os(tvOS)
    try storyboard.validate()
    #endif
  }

  #if os(iOS) || os(tvOS)
  struct nib: Rswift.Validatable {
    static func validate() throws {
      try _AlertView.validate()
      try _BaseDetailsTableViewCell.validate()
      try _EatListBlankTableViewCell.validate()
      try _EatListTableViewCell.validate()
    }

    struct _AddressDetailsTableViewCell: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "AddressDetailsTableViewCell"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> AddressDetailsTableViewCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? AddressDetailsTableViewCell
      }

      fileprivate init() {}
    }

    struct _AlertView: Rswift.NibResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let name = "AlertView"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
      }

      func secondView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[1] as? UIKit.UIView
      }

      static func validate() throws {
        if UIKit.UIImage(named: "ErrorIcon", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'ErrorIcon' is used in nib 'AlertView', but couldn't be loaded.") }
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }

    struct _BaseDetailsTableViewCell: Rswift.NibResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let name = "BaseDetailsTableViewCell"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> BaseDetailsTableViewCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? BaseDetailsTableViewCell
      }

      static func validate() throws {
        if UIKit.UIImage(named: "Rating", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'Rating' is used in nib 'BaseDetailsTableViewCell', but couldn't be loaded.") }
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }

    struct _EatListBlankTableViewCell: Rswift.NibResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let name = "EatListBlankTableViewCell"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> EatListBlankTableViewCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? EatListBlankTableViewCell
      }

      static func validate() throws {
        if UIKit.UIImage(named: "BlankState", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'BlankState' is used in nib 'EatListBlankTableViewCell', but couldn't be loaded.") }
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }

    struct _EatListTableViewCell: Rswift.NibResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let name = "EatListTableViewCell"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> EatListTableViewCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? EatListTableViewCell
      }

      static func validate() throws {
        if UIKit.UIImage(named: "Rating", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'Rating' is used in nib 'EatListTableViewCell', but couldn't be loaded.") }
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }

    struct _HighlightsTableViewCell: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "HighlightsTableViewCell"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> HighlightsTableViewCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? HighlightsTableViewCell
      }

      fileprivate init() {}
    }

    struct _ImageHeaderTableViewCell: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "ImageHeaderTableViewCell"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> ImageHeaderTableViewCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? ImageHeaderTableViewCell
      }

      fileprivate init() {}
    }

    struct _SimpleCarouselItemCell: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "SimpleCarouselItemCell"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> SimpleCarouselItemCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? SimpleCarouselItemCell
      }

      fileprivate init() {}
    }

    struct _SimpleCarouselItemView: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "SimpleCarouselItemView"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }
  #endif

  #if os(iOS) || os(tvOS)
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      #if os(iOS) || os(tvOS)
      try eatList.validate()
      #endif
      #if os(iOS) || os(tvOS)
      try launchScreen.validate()
      #endif
      #if os(iOS) || os(tvOS)
      try targetDetails.validate()
      #endif
    }

    #if os(iOS) || os(tvOS)
    struct eatList: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = EatListViewController

      let bundle = R.hostingBundle
      let name = "EatList"

      static func validate() throws {
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }
    #endif

    #if os(iOS) || os(tvOS)
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController

      let bundle = R.hostingBundle
      let name = "LaunchScreen"

      static func validate() throws {
        if UIKit.UIImage(named: "Icon", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'Icon' is used in storyboard 'LaunchScreen', but couldn't be loaded.") }
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }
    #endif

    #if os(iOS) || os(tvOS)
    struct targetDetails: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = TargetDetailsViewController

      let bundle = R.hostingBundle
      let name = "TargetDetails"

      static func validate() throws {
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }
    #endif

    fileprivate init() {}
  }
  #endif

  fileprivate init() {}
}
